In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(3,)

In [6]:
arr.ndim

1

In [8]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [9]:
arr1.ndim

2

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
np.full((2,3,3),10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(3,2)

array([[0.4110659 , 0.77519252],
       [0.15739527, 0.38958855],
       [0.95562415, 0.15210137]])

In [21]:
np.random.randint(1,10,size=(3,2))

array([[2, 5],
       [7, 5],
       [1, 9]], dtype=int32)

In [22]:
arr = np.array([1, 2, 3])

In [23]:
arr *10


array([10, 20, 30])

In [24]:
arr/0

C:\Users\scl\AppData\Local\Temp\ipykernel_50424\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf])

In [25]:
arr

array([1, 2, 3])

In [26]:
arr+4

array([5, 6, 7])

In [27]:
arr

array([1, 2, 3])

In [28]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081])

In [29]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [30]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229])

In [31]:
np.mean(arr)

np.float64(2.0)

In [32]:
np.median(arr)

np.float64(2.0)

In [33]:
np.std(arr)


np.float64(0.816496580927726)

In [34]:
np.sum(arr)

np.int64(6)

In [35]:
np.min(arr)

np.int64(1)

In [36]:
np.max(arr)

np.int64(3)

In [42]:
list(range(1,10,.5))

TypeError: 'float' object cannot be interpreted as an integer

In [49]:
arr = np.arange(1,13)

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
arr.shape

(12,)

In [52]:
arr.ndim

1

In [53]:
arr.reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
arr.reshape(1,2,6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]])

In [58]:
arr.reshape(1,4,-156764)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr = np.array([4,5,6,7,8,9,0,2,3,4,5,56,67,78,89,90])

In [60]:
arr[0]

np.int64(4)

In [61]:
arr[0:5]

array([4, 5, 6, 7, 8])

In [62]:
arr[arr % 2 == 0]

array([ 4,  6,  8,  0,  2,  4, 56, 78, 90])

In [63]:
arr.shape

(16,)

In [64]:
arr.reshape(4,4)

array([[ 4,  5,  6,  7],
       [ 8,  9,  0,  2],
       [ 3,  4,  5, 56],
       [67, 78, 89, 90]])

In [66]:
arr.reshape(2,8)

array([[ 4,  5,  6,  7,  8,  9,  0,  2],
       [ 3,  4,  5, 56, 67, 78, 89, 90]])

In [67]:
arr.reshape(2,-1)

array([[ 4,  5,  6,  7,  8,  9,  0,  2],
       [ 3,  4,  5, 56, 67, 78, 89, 90]])

In [68]:
arr.reshape(-1,2)

array([[ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 0,  2],
       [ 3,  4],
       [ 5, 56],
       [67, 78],
       [89, 90]])

In [69]:
arr

array([ 4,  5,  6,  7,  8,  9,  0,  2,  3,  4,  5, 56, 67, 78, 89, 90])

In [70]:
np.where(arr % 2 == 0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even'], dtype='<U4')

In [71]:
np.where(arr >10 ,'high', 'low')

array(['low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'high', 'high', 'high', 'high', 'high'], dtype='<U4')