In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.pipeline import Pipeline

from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

import joblib
import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

In [ ]:
n=1200

In [14]:
legit_amount = np.random.normal(loc = 1200, scale = 600, size = n).clip(50,10000)

In [15]:
len(legit_amount)

1200

In [16]:
legit_hours = np.random.randint(7,22, n)

In [17]:
legit_hours

array([ 8,  7, 18, ..., 15, 21, 20], shape=(1200,), dtype=int32)

In [18]:
legit_merchant_risk = np.random.normal(loc = 25,scale = 10, size = n).clip(1,70)

In [19]:
legit_merchant_risk

array([21.34322917, 30.04270748, 30.21449399, ..., 27.54731137,
       23.71122621, 19.90906195], shape=(1200,))

In [20]:
legit_user_avg = np.random.normal(loc = 3000, scale = 1500, size = n).clip(100,15000)

In [21]:
fraud_amount = np.random.normal(loc = 4000, scale = 2000, size = n).clip(100,20000)
fraud_hours = np.random.choice(
    [0,1,2,3,4,5,6,23], size = n, p = [0.15,0.15,0.15,0.15,0.1,0.1,0.1,0.1]
)
fraud_merchant_risk = np.random.normal(loc = 70, scale = 15, size = n).clip(30,100)
fraud_user_avg = np.random.normal(loc = 800, scale = 400, size = n).clip(50,5000)

In [22]:
x = np.vstack([
    np.column_stack([legit_amount, legit_hours, legit_merchant_risk, legit_user_avg]),
    np.column_stack([fraud_amount, fraud_hours, fraud_merchant_risk, fraud_user_avg])
])

In [23]:
x

array([[1.53978392e+03, 8.00000000e+00, 2.13432292e+01, 3.72803986e+03],
       [8.66931758e+02, 7.00000000e+00, 3.00427075e+01, 1.72634272e+03],
       [9.22056518e+02, 1.80000000e+01, 3.02144940e+01, 3.45849835e+03],
       ...,
       [5.28877691e+03, 1.00000000e+00, 8.22202666e+01, 5.67422765e+02],
       [2.64301054e+03, 4.00000000e+00, 6.53318757e+01, 5.00000000e+01],
       [3.38900107e+03, 3.00000000e+00, 5.36342992e+01, 5.69876557e+02]],
      shape=(2400, 4))

In [24]:
y_labels= np.array(["legit"]*n+["Fraud"]*n)

In [25]:
y_labels

array(['legit', 'legit', 'legit', ..., 'Fraud', 'Fraud', 'Fraud'],
      shape=(2400,), dtype='<U5')

In [31]:
df = pd.DataFrame(x,columns=["amount_inr","txn_hour","merchant_risk_score","user_avg_txn"])

In [32]:
df

,amount_inr,txn_hour,merchant_risk_score,user_avg_txn
0,1539.783923,8.0,21.343229,3728.039861
1,866.931758,7.0,30.042707,1726.342724
2,922.056518,18.0,30.214494,3458.498353
3,1661.547384,9.0,38.369691,1903.118147
4,1275.847698,13.0,24.177463,1653.510922
...,...,...,...,...
2395,2589.366552,4.0,80.514585,944.980347
2396,4991.531146,5.0,86.100103,794.029851
2397,5288.776907,1.0,82.220267,567.422765
2398,2643.010539,4.0,65.331876,50.000000


In [33]:
df["label"] = y_labels

In [30]:
y_labels

array(['legit', 'legit', 'legit', ..., 'Fraud', 'Fraud', 'Fraud'],
      shape=(2400,), dtype='<U5')

In [34]:
df

,amount_inr,txn_hour,merchant_risk_score,user_avg_txn,label
0,1539.783923,8.0,21.343229,3728.039861,legit
1,866.931758,7.0,30.042707,1726.342724,legit
2,922.056518,18.0,30.214494,3458.498353,legit
3,1661.547384,9.0,38.369691,1903.118147,legit
4,1275.847698,13.0,24.177463,1653.510922,legit
...,...,...,...,...,...
2395,2589.366552,4.0,80.514585,944.980347,Fraud
2396,4991.531146,5.0,86.100103,794.029851,Fraud
2397,5288.776907,1.0,82.220267,567.422765,Fraud
2398,2643.010539,4.0,65.331876,50.000000,Fraud


In [35]:
x = df.drop("label", axis=1)
y = df["label"]

In [36]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [42]:
base_model = Pipeline(steps=[
    ('svc', SVC(kernel='rbf',probability=True))
])

In [43]:
base_model

,steps,"[('svc', ...)]"
,transform_input,None
,memory,None
,verbose,False
,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,True


In [44]:
base_model.fit(x_train, y_train)

,steps,"[('svc', ...)]"
,transform_input,None
,memory,None
,verbose,False
,C,1.0
,kernel,'rbf'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,True


In [45]:
base_model.predict(x_test)

array(['Fraud', 'Fraud', 'legit', 'Fraud', 'Fraud', 'legit', 'Fraud',
       'Fraud', 'Fraud', 'legit', 'Fraud', 'legit', 'legit', 'Fraud',
       'Fraud', 'Fraud', 'legit', 'Fraud', 'Fraud', 'Fraud', 'legit',
       'Fraud', 'legit', 'Fraud', 'Fraud', 'legit', 'Fraud', 'Fraud',
       'Fraud', 'Fraud', 'Fraud', 'legit', 'Fraud', 'legit', 'legit',
       'Fraud', 'legit', 'legit', 'legit', 'legit', 'legit', 'Fraud',
       'legit', 'legit', 'legit', 'legit', 'Fraud', 'Fraud', 'Fraud',
       'legit', 'legit', 'Fraud', 'Fraud', 'Fraud', 'Fraud', 'Fraud',
       'Fraud', 'Fraud', 'Fraud', 'Fraud', 'Fraud', 'legit', 'Fraud',
       'Fraud', 'Fraud', 'Fraud', 'Fraud', 'legit', 'Fraud', 'legit',
       'Fraud', 'Fraud', 'Fraud', 'Fraud', 'legit', 'legit', 'Fraud',
       'legit', 'legit', 'Fraud', 'legit', 'legit', 'Fraud', 'legit',
       'legit', 'legit', 'legit', 'legit', 'legit', 'Fraud', 'Fraud',
       'legit', 'legit', 'Fraud', 'Fraud', 'Fraud', 'legit', 'Fraud',
       'Fraud', 'Fra

In [46]:
accuracy = base_model.score(x_test, y_test)
print(f"Model accuracy: {accuracy*100:.2f}%")

Model accuracy: 91.46%


In [49]:
grid = GridSearchCV(
    estimator=base_model,
    param_grid={
        'svc__C': [0.1, 1, 10, 100],
        'svc__gamma': [1, 0.1, 0.01, 0.001],
        'svc__kernel': ['rbf','linear'],
        'svc__degree': [2,3,4]
    },
    cv = 5,
    scoring='accuracy',
    verbose=2,
    n_jobs=-1
)

In [50]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 96 candidates, totalling 480 fits


,estimator,Pipeline(step...ility=True))])
,param_grid,"{'svc__C': [0.1, 1, ...], 'svc__degree': [2, 3, ...], 'svc__gamma': [1, 0.1, ...], 'svc__kernel': ['rbf', 'linear']}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,5
,verbose,2
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,C,1


In [52]:
best_model = grid.best_estimator_

In [53]:
grid.best_params_

{'svc__C': 1, 'svc__degree': 2, 'svc__gamma': 1, 'svc__kernel': 'linear'}

In [54]:
grid.best_score_

np.float64(0.99375)

In [55]:
accuracy_score = best_model.score(x_test, y_test)
print(f"Optimized Model accuracy: {accuracy_score*100:.2f}%")

Optimized Model accuracy: 98.96%


In [56]:
joblib.dump(best_model, "svc_fraud_model.pkl")

['svc_fraud_model.pkl']